default_install_hook_types: [pre-commit, pre-push, commit-msg]
fail_fast: true
repos:
-   repo: local
    hooks:
    -   id: tf-docs
        name: generate terraform documentation
        language: system
        entry: make generate-docs
        require_serial: true
        pass_filenames: false
        stages: [pre-commit]
    -   id: check-tf-examples
        name: check terraform examples
        language: system
        entry: make check-example-usage
        require_serial: true
        pass_filenames: false
        stages: [pre-commit]
    -   id: check-tf-docs
        name: check terraform documentation subcategory
        language: system
        entry: make check-empty-subcategory
        require_serial: true
        pass_filenames: false
        stages: [pre-commit]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit, pre-push]
        exclude: >
         (?x)(
            ^mgc/sdk/version.txt|
            ^script-qa/
            ^mgc/cli/docs/|
          )
    -   id: end-of-file-fixer
        stages: [pre-commit, pre-push]
        exclude: >
          (?x)(
            ^mgc/sdk/version.txt|
            ^script-qa/
            ^mgc/cli/docs/|
          )
    -   id: check-yaml
        stages: [pre-commit, pre-push]
    -   id: check-added-large-files
        exclude: ^script-qa/
        stages: [pre-commit, pre-push]
    -   id: check-shebang-scripts-are-executable
        stages: [pre-commit, pre-push]
    -   id: check-merge-conflict
        stages: [pre-commit, pre-push]
    -   id: mixed-line-ending
        stages: [pre-commit, pre-push]

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
    -   id: golangci-lint
        stages: [pre-commit]
        # Need to specify manually due to this issue:
        # https://github.com/golangci/golangci-lint/issues/2654
        entry: bash -c "go list -f '{{.Dir}}/...' -m | xargs golangci-lint run --fix --new-from-rev HEAD"

-   repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0
    hooks:
    -   id: golangci-lint
        stages: [pre-push]
        # Need to specify manually due to this issue:
        # https://github.com/golangci/golangci-lint/issues/2654
        entry: bash -c "go list -f '{{.Dir}}/...' -m | xargs golangci-lint run --fix"

-   repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    -   id: go-mod-tidy
        stages: [pre-commit]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.10.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

