// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	containerregistry "github.com/MagaluCloud/mgc-sdk-go/containerregistry"

	helpers "github.com/MagaluCloud/mgc-sdk-go/helpers"

	mock "github.com/stretchr/testify/mock"
)

// ImagesService is an autogenerated mock type for the ImagesService type
type ImagesService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, registryID, repositoryName, digestOrTag
func (_m *ImagesService) Delete(ctx context.Context, registryID string, repositoryName string, digestOrTag string) error {
	ret := _m.Called(ctx, registryID, repositoryName, digestOrTag)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, registryID, repositoryName, digestOrTag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, registryID, repositoryName, digestOrTag
func (_m *ImagesService) Get(ctx context.Context, registryID string, repositoryName string, digestOrTag string) (*containerregistry.ImageResponse, error) {
	ret := _m.Called(ctx, registryID, repositoryName, digestOrTag)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *containerregistry.ImageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*containerregistry.ImageResponse, error)); ok {
		return rf(ctx, registryID, repositoryName, digestOrTag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *containerregistry.ImageResponse); ok {
		r0 = rf(ctx, registryID, repositoryName, digestOrTag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.ImageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, registryID, repositoryName, digestOrTag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, registryID, repositoryName, opts
func (_m *ImagesService) List(ctx context.Context, registryID string, repositoryName string, opts containerregistry.ImageListOptions) (*helpers.PaginatedResponse[containerregistry.ImageResponse], error) {
	ret := _m.Called(ctx, registryID, repositoryName, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *helpers.PaginatedResponse[containerregistry.ImageResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, containerregistry.ImageListOptions) (*helpers.PaginatedResponse[containerregistry.ImageResponse], error)); ok {
		return rf(ctx, registryID, repositoryName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, containerregistry.ImageListOptions) *helpers.PaginatedResponse[containerregistry.ImageResponse]); ok {
		r0 = rf(ctx, registryID, repositoryName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helpers.PaginatedResponse[containerregistry.ImageResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, containerregistry.ImageListOptions) error); ok {
		r1 = rf(ctx, registryID, repositoryName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx, registryID, repositoryName, filterOpts
func (_m *ImagesService) ListAll(ctx context.Context, registryID string, repositoryName string, filterOpts containerregistry.ImageFilterOptions) ([]containerregistry.ImageResponse, error) {
	ret := _m.Called(ctx, registryID, repositoryName, filterOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []containerregistry.ImageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, containerregistry.ImageFilterOptions) ([]containerregistry.ImageResponse, error)); ok {
		return rf(ctx, registryID, repositoryName, filterOpts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, containerregistry.ImageFilterOptions) []containerregistry.ImageResponse); ok {
		r0 = rf(ctx, registryID, repositoryName, filterOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]containerregistry.ImageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, containerregistry.ImageFilterOptions) error); ok {
		r1 = rf(ctx, registryID, repositoryName, filterOpts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImagesService creates a new instance of ImagesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImagesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImagesService {
	mock := &ImagesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
