// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sshkeys "github.com/MagaluCloud/mgc-sdk-go/sshkeys"
	mock "github.com/stretchr/testify/mock"
)

// KeyService is an autogenerated mock type for the KeyService type
type KeyService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *KeyService) Create(ctx context.Context, req sshkeys.CreateSSHKeyRequest) (*sshkeys.SSHKey, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sshkeys.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sshkeys.CreateSSHKeyRequest) (*sshkeys.SSHKey, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sshkeys.CreateSSHKeyRequest) *sshkeys.SSHKey); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sshkeys.SSHKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sshkeys.CreateSSHKeyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, keyID
func (_m *KeyService) Delete(ctx context.Context, keyID string) (*sshkeys.SSHKey, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *sshkeys.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sshkeys.SSHKey, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sshkeys.SSHKey); ok {
		r0 = rf(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sshkeys.SSHKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, keyID
func (_m *KeyService) Get(ctx context.Context, keyID string) (*sshkeys.SSHKey, error) {
	ret := _m.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sshkeys.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*sshkeys.SSHKey, error)); ok {
		return rf(ctx, keyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *sshkeys.SSHKey); ok {
		r0 = rf(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sshkeys.SSHKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *KeyService) List(ctx context.Context, opts sshkeys.ListOptions) ([]sshkeys.SSHKey, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []sshkeys.SSHKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sshkeys.ListOptions) ([]sshkeys.SSHKey, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sshkeys.ListOptions) []sshkeys.SSHKey); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sshkeys.SSHKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sshkeys.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKeyService creates a new instance of KeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyService {
	mock := &KeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
