// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	containerregistry "github.com/MagaluCloud/mgc-sdk-go/containerregistry"

	mock "github.com/stretchr/testify/mock"
)

// ProxyCachesService is an autogenerated mock type for the ProxyCachesService type
type ProxyCachesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *ProxyCachesService) Create(ctx context.Context, req containerregistry.CreateProxyCacheRequest) (*containerregistry.CreateProxyCacheResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *containerregistry.CreateProxyCacheResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.CreateProxyCacheRequest) (*containerregistry.CreateProxyCacheResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.CreateProxyCacheRequest) *containerregistry.CreateProxyCacheResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.CreateProxyCacheResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, containerregistry.CreateProxyCacheRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateStatus provides a mock function with given fields: ctx, req
func (_m *ProxyCachesService) CreateStatus(ctx context.Context, req containerregistry.CreateProxyCacheStatusRequest) (*containerregistry.CreateProxyCacheStatusResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateStatus")
	}

	var r0 *containerregistry.CreateProxyCacheStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.CreateProxyCacheStatusRequest) (*containerregistry.CreateProxyCacheStatusResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.CreateProxyCacheStatusRequest) *containerregistry.CreateProxyCacheStatusResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.CreateProxyCacheStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, containerregistry.CreateProxyCacheStatusRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ProxyCachesService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *ProxyCachesService) Get(ctx context.Context, id string) (*containerregistry.GetProxyCacheResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *containerregistry.GetProxyCacheResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*containerregistry.GetProxyCacheResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *containerregistry.GetProxyCacheResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.GetProxyCacheResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *ProxyCachesService) List(ctx context.Context, opts containerregistry.ProxyCacheListOptions) (*containerregistry.ListProxyCachesResponse, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *containerregistry.ListProxyCachesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.ProxyCacheListOptions) (*containerregistry.ListProxyCachesResponse, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.ProxyCacheListOptions) *containerregistry.ListProxyCachesResponse); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.ListProxyCachesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, containerregistry.ProxyCacheListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx, opts
func (_m *ProxyCachesService) ListAll(ctx context.Context, opts containerregistry.ProxyCacheListAllOptions) ([]containerregistry.ProxyCache, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []containerregistry.ProxyCache
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.ProxyCacheListAllOptions) ([]containerregistry.ProxyCache, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.ProxyCacheListAllOptions) []containerregistry.ProxyCache); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]containerregistry.ProxyCache)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, containerregistry.ProxyCacheListAllOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListStatus provides a mock function with given fields: ctx, id
func (_m *ProxyCachesService) ListStatus(ctx context.Context, id string) (*containerregistry.ListProxyCacheStatusResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ListStatus")
	}

	var r0 *containerregistry.ListProxyCacheStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*containerregistry.ListProxyCacheStatusResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *containerregistry.ListProxyCacheStatusResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.ListProxyCacheStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *ProxyCachesService) Update(ctx context.Context, id string, req containerregistry.UpdateProxyCacheRequest) (*containerregistry.ProxyCache, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *containerregistry.ProxyCache
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, containerregistry.UpdateProxyCacheRequest) (*containerregistry.ProxyCache, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, containerregistry.UpdateProxyCacheRequest) *containerregistry.ProxyCache); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.ProxyCache)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, containerregistry.UpdateProxyCacheRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProxyCachesService creates a new instance of ProxyCachesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyCachesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyCachesService {
	mock := &ProxyCachesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
