// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	containerregistry "github.com/MagaluCloud/mgc-sdk-go/containerregistry"

	helpers "github.com/MagaluCloud/mgc-sdk-go/helpers"

	mock "github.com/stretchr/testify/mock"
)

// RegistriesService is an autogenerated mock type for the RegistriesService type
type RegistriesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *RegistriesService) Create(ctx context.Context, request *containerregistry.RegistryRequest) (*containerregistry.RegistryResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *containerregistry.RegistryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *containerregistry.RegistryRequest) (*containerregistry.RegistryResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *containerregistry.RegistryRequest) *containerregistry.RegistryResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.RegistryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *containerregistry.RegistryRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, registryID
func (_m *RegistriesService) Delete(ctx context.Context, registryID string) error {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, registryID
func (_m *RegistriesService) Get(ctx context.Context, registryID string) (*containerregistry.RegistryResponse, error) {
	ret := _m.Called(ctx, registryID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *containerregistry.RegistryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*containerregistry.RegistryResponse, error)); ok {
		return rf(ctx, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *containerregistry.RegistryResponse); ok {
		r0 = rf(ctx, registryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.RegistryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *RegistriesService) List(ctx context.Context, opts containerregistry.RegistryListOptions) (*helpers.PaginatedResponse[containerregistry.RegistryResponse], error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *helpers.PaginatedResponse[containerregistry.RegistryResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.RegistryListOptions) (*helpers.PaginatedResponse[containerregistry.RegistryResponse], error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.RegistryListOptions) *helpers.PaginatedResponse[containerregistry.RegistryResponse]); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helpers.PaginatedResponse[containerregistry.RegistryResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, containerregistry.RegistryListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx, filterOpts
func (_m *RegistriesService) ListAll(ctx context.Context, filterOpts containerregistry.RegistryFilterOptions) ([]containerregistry.RegistryResponse, error) {
	ret := _m.Called(ctx, filterOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []containerregistry.RegistryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.RegistryFilterOptions) ([]containerregistry.RegistryResponse, error)); ok {
		return rf(ctx, filterOpts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, containerregistry.RegistryFilterOptions) []containerregistry.RegistryResponse); ok {
		r0 = rf(ctx, filterOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]containerregistry.RegistryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, containerregistry.RegistryFilterOptions) error); ok {
		r1 = rf(ctx, filterOpts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRegistriesService creates a new instance of RegistriesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistriesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistriesService {
	mock := &RegistriesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
