// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	containerregistry "github.com/MagaluCloud/mgc-sdk-go/containerregistry"

	helpers "github.com/MagaluCloud/mgc-sdk-go/helpers"

	mock "github.com/stretchr/testify/mock"
)

// RepositoriesService is an autogenerated mock type for the RepositoriesService type
type RepositoriesService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, registryID, repositoryName
func (_m *RepositoriesService) Delete(ctx context.Context, registryID string, repositoryName string) error {
	ret := _m.Called(ctx, registryID, repositoryName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, registryID, repositoryName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, registryID, repositoryName
func (_m *RepositoriesService) Get(ctx context.Context, registryID string, repositoryName string) (*containerregistry.RepositoryResponse, error) {
	ret := _m.Called(ctx, registryID, repositoryName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *containerregistry.RepositoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*containerregistry.RepositoryResponse, error)); ok {
		return rf(ctx, registryID, repositoryName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *containerregistry.RepositoryResponse); ok {
		r0 = rf(ctx, registryID, repositoryName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*containerregistry.RepositoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, registryID, repositoryName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, registryID, opts
func (_m *RepositoriesService) List(ctx context.Context, registryID string, opts containerregistry.RepositoryListOptions) (*helpers.PaginatedResponse[containerregistry.RepositoryResponse], error) {
	ret := _m.Called(ctx, registryID, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *helpers.PaginatedResponse[containerregistry.RepositoryResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, containerregistry.RepositoryListOptions) (*helpers.PaginatedResponse[containerregistry.RepositoryResponse], error)); ok {
		return rf(ctx, registryID, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, containerregistry.RepositoryListOptions) *helpers.PaginatedResponse[containerregistry.RepositoryResponse]); ok {
		r0 = rf(ctx, registryID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helpers.PaginatedResponse[containerregistry.RepositoryResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, containerregistry.RepositoryListOptions) error); ok {
		r1 = rf(ctx, registryID, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: ctx, registryID, filterOpts
func (_m *RepositoriesService) ListAll(ctx context.Context, registryID string, filterOpts containerregistry.RepositoryFilterOptions) ([]containerregistry.RepositoryResponse, error) {
	ret := _m.Called(ctx, registryID, filterOpts)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []containerregistry.RepositoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, containerregistry.RepositoryFilterOptions) ([]containerregistry.RepositoryResponse, error)); ok {
		return rf(ctx, registryID, filterOpts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, containerregistry.RepositoryFilterOptions) []containerregistry.RepositoryResponse); ok {
		r0 = rf(ctx, registryID, filterOpts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]containerregistry.RepositoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, containerregistry.RepositoryFilterOptions) error); ok {
		r1 = rf(ctx, registryID, filterOpts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoriesService creates a new instance of RepositoriesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoriesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoriesService {
	mock := &RepositoriesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
