// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	tag "github.com/MagaluCloud/mgc-sdk-go/tag"
	mock "github.com/stretchr/testify/mock"
)

// ResourceService is an autogenerated mock type for the ResourceService type
type ResourceService struct {
	mock.Mock
}

// AttachTags provides a mock function with given fields: ctx, externalID, req
func (_m *ResourceService) AttachTags(ctx context.Context, externalID string, req tag.AttachTagsRequest) (*tag.Resource, error) {
	ret := _m.Called(ctx, externalID, req)

	if len(ret) == 0 {
		panic("no return value specified for AttachTags")
	}

	var r0 *tag.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.AttachTagsRequest) (*tag.Resource, error)); ok {
		return rf(ctx, externalID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.AttachTagsRequest) *tag.Resource); ok {
		r0 = rf(ctx, externalID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, tag.AttachTagsRequest) error); ok {
		r1 = rf(ctx, externalID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DetachTag provides a mock function with given fields: ctx, externalID, tagName
func (_m *ResourceService) DetachTag(ctx context.Context, externalID string, tagName string) error {
	ret := _m.Called(ctx, externalID, tagName)

	if len(ret) == 0 {
		panic("no return value specified for DetachTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, externalID, tagName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, externalID
func (_m *ResourceService) Get(ctx context.Context, externalID string) (*tag.Resource, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *tag.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tag.Resource, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tag.Resource); ok {
		r0 = rf(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *ResourceService) List(ctx context.Context, opts tag.ListResourcesOptions) ([]tag.Resource, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []tag.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListResourcesOptions) ([]tag.Resource, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListResourcesOptions) []tag.Resource); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tag.ListResourcesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResourceService creates a new instance of ResourceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceService {
	mock := &ResourceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
