// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	tag "github.com/MagaluCloud/mgc-sdk-go/tag"
	mock "github.com/stretchr/testify/mock"
)

// ResourceTypeService is an autogenerated mock type for the ResourceTypeService type
type ResourceTypeService struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, opts
func (_m *ResourceTypeService) List(ctx context.Context, opts tag.ListResourceTypesOptions) ([]tag.ResourceType, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []tag.ResourceType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListResourceTypesOptions) ([]tag.ResourceType, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListResourceTypesOptions) []tag.ResourceType); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.ResourceType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tag.ListResourceTypesOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResourceTypeService creates a new instance of ResourceTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceTypeService {
	mock := &ResourceTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
