// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	tag "github.com/MagaluCloud/mgc-sdk-go/tag"
	mock "github.com/stretchr/testify/mock"
)

// TagService is an autogenerated mock type for the TagService type
type TagService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *TagService) Create(ctx context.Context, req tag.CreateTagRequest) (*tag.Tag, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tag.CreateTagRequest) (*tag.Tag, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tag.CreateTagRequest) *tag.Tag); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tag.CreateTagRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, tagName
func (_m *TagService) Delete(ctx context.Context, tagName string) error {
	ret := _m.Called(ctx, tagName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tagName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, tagName
func (_m *TagService) Get(ctx context.Context, tagName string) (*tag.Tag, error) {
	ret := _m.Called(ctx, tagName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tag.Tag, error)); ok {
		return rf(ctx, tagName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tag.Tag); ok {
		r0 = rf(ctx, tagName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tagName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *TagService) List(ctx context.Context, opts tag.ListTagsOptions) ([]tag.Tag, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListTagsOptions) ([]tag.Tag, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tag.ListTagsOptions) []tag.Tag); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tag.ListTagsOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tagName, req
func (_m *TagService) Update(ctx context.Context, tagName string, req tag.UpdateTagRequest) (*tag.Tag, error) {
	ret := _m.Called(ctx, tagName, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *tag.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.UpdateTagRequest) (*tag.Tag, error)); ok {
		return rf(ctx, tagName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.UpdateTagRequest) *tag.Tag); ok {
		r0 = rf(ctx, tagName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, tag.UpdateTagRequest) error); ok {
		r1 = rf(ctx, tagName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTagService creates a new instance of TagService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagService {
	mock := &TagService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
