// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	tag "github.com/MagaluCloud/mgc-sdk-go/tag"
	mock "github.com/stretchr/testify/mock"
)

// TagValueService is an autogenerated mock type for the TagValueService type
type TagValueService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, tagName, req
func (_m *TagValueService) Create(ctx context.Context, tagName string, req tag.CreateTagValueRequest) (*tag.TagValue, error) {
	ret := _m.Called(ctx, tagName, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tag.TagValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.CreateTagValueRequest) (*tag.TagValue, error)); ok {
		return rf(ctx, tagName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.CreateTagValueRequest) *tag.TagValue); ok {
		r0 = rf(ctx, tagName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.TagValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, tag.CreateTagValueRequest) error); ok {
		r1 = rf(ctx, tagName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, tagName, valueName
func (_m *TagValueService) Delete(ctx context.Context, tagName string, valueName string) error {
	ret := _m.Called(ctx, tagName, valueName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tagName, valueName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, tagName, valueName
func (_m *TagValueService) Get(ctx context.Context, tagName string, valueName string) (*tag.TagValue, error) {
	ret := _m.Called(ctx, tagName, valueName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *tag.TagValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*tag.TagValue, error)); ok {
		return rf(ctx, tagName, valueName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *tag.TagValue); ok {
		r0 = rf(ctx, tagName, valueName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.TagValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tagName, valueName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, tagName, opts
func (_m *TagValueService) List(ctx context.Context, tagName string, opts tag.ListTagValuesOptions) ([]tag.TagValue, error) {
	ret := _m.Called(ctx, tagName, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []tag.TagValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.ListTagValuesOptions) ([]tag.TagValue, error)); ok {
		return rf(ctx, tagName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, tag.ListTagValuesOptions) []tag.TagValue); ok {
		r0 = rf(ctx, tagName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tag.TagValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, tag.ListTagValuesOptions) error); ok {
		r1 = rf(ctx, tagName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, tagName, valueName, req
func (_m *TagValueService) Update(ctx context.Context, tagName string, valueName string, req tag.UpdateTagValueRequest) (*tag.TagValue, error) {
	ret := _m.Called(ctx, tagName, valueName, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *tag.TagValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, tag.UpdateTagValueRequest) (*tag.TagValue, error)); ok {
		return rf(ctx, tagName, valueName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, tag.UpdateTagValueRequest) *tag.TagValue); ok {
		r0 = rf(ctx, tagName, valueName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tag.TagValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, tag.UpdateTagValueRequest) error); ok {
		r1 = rf(ctx, tagName, valueName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTagValueService creates a new instance of TagValueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagValueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagValueService {
	mock := &TagValueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
