name: Validate Pre Commit Hooks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ci-check-${{ github.ref }}
  
jobs:
  validate:
    name: Run Pre Commit Hooks
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GH_PAT2 }}
          fetch-depth: 1
      - uses: actions/setup-python@v5.2.0   
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies       
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: "Go Imports"
        run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: pre-commit/action@v3.0.1
        name: "Pre-commit run"
        with:
          extra_args: --show-diff-on-failure --color=always --hook-stage push --all-files
