name: Release CLI and Terraform

on:
  workflow_dispatch:
    inputs:
      runTerraform:
        description: "Run deploy of Terraform"
        type: boolean
        required: false

concurrency:
  group: ci-check-${{ github.ref }}

jobs:
  build:
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable

  terraform-release:
    needs: build
    runs-on: ${{ vars.RUNNER_RUNS_ON }}
    timeout-minutes: 20
    if: ${{ inputs.runTerraform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          cache-dependency-path: "**/go.sum"
          go-version: stable
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2
          args: release --clean --config="goreleaser_terraform.yaml"
        env:
          VERSION: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}